apiVersion: apps/v1
kind: Deployment
metadata:
  name: "rp-campaign-manager"
  namespace: rp-campaign-manager
spec:
  selector:
    matchLabels:
      app: "rp-campaign-manager"
  template:
    metadata:
      labels:
        app: "rp-campaign-manager"
    spec:
      containers:
        - name: "rp-campaign-manager"
          image: "docker.pkg.github.com/fzymgc/package-repository/rp-campaign-manager"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "rp-campaign-manager"
  namespace: rp-campaign-manager
spec:
  selector:
    app: "rp-campaign-manager"
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rp-campaign-manager-ingress
  namespace: rp-campaign-manager
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: rp-campaign-manager.test
    http:
      paths:
      - path: /
        backend:
          serviceName: rp-campaign-manager
          servicePort: 8080
