---
# Source: mongodb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: main-mongodb
  namespace: rp-campaign-manager
  labels:
    app: mongodb
    chart: mongodb-7.6.2
    release: "main"
    heritage: "Helm"
type: Opaque
data:
  mongodb-root-password:  "c2VjcmV0cGFzc3dvcmQ="
  mongodb-password:  "bXktcGFzc3dvcmQ="
---
# Source: mongodb/templates/pvc-standalone.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: mongodb
    chart: mongodb-7.6.2
    heritage: Helm
    release: main
  name: main-mongodb
  namespace: rp-campaign-manager
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
---
# Source: mongodb/templates/svc-standalone.yaml
apiVersion: v1
kind: Service
metadata:
  name: main-mongodb
  namespace: rp-campaign-manager
  labels:
    app: mongodb
    chart: mongodb-7.6.2
    release: "main"
    heritage: "Helm"
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: mongodb
    release: "main"
---
# Source: mongodb/templates/deployment-standalone.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-mongodb
  namespace: rp-campaign-manager
  labels:
    app: mongodb
    chart: mongodb-7.6.2
    release: "main"
    heritage: "Helm"
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mongodb
      release: "main"
  template:
    metadata:
      labels:
        app: mongodb
        release: "main"
        chart: mongodb-7.6.2
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: main-mongodb
        image: docker.io/bitnami/mongodb:4.0.14-debian-9-r0
        imagePullPolicy: "IfNotPresent"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: main-mongodb
              key: mongodb-password
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: main-mongodb
              key: mongodb-root-password
        - name: MONGODB_USERNAME
          value: "app"
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_DATABASE
          value: "rp-campaign-manager"
        - name: MONGODB_ENABLE_IPV6
          value: "no"
        - name: MONGODB_ENABLE_DIRECTORY_PER_DB
          value: "no"
        ports:
        - name: mongodb
          containerPort: 27017
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        volumeMounts:
        - name: data
          mountPath: /bitnami/mongodb
        resources:
          {}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: main-mongodb
