name: Main CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        clean: true
        lfs: true
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true
      run: ./gradlew build
    - name: Publish Docker Image
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true
        GPR_USERNAME: fzymgc
        GPR_PASSWORD: ${{secrets.GITHUB_TOKEN}}
      run: ./gradlew jib
